
    ## Get ip from inventory file for first host in lead group
    #leader_ip: {{ hostvars[groups['lead'][0]]['ansible_default_ipv4']['address'] }}
      #when:  join_cmd.stdout == ''
      #when: join_cmd.stdout is search('')
      #notify: join swarm
      #      #- name: upload template
      #      #  template:
      #      #    src: ../templatefiles/swarm.sh
      #      #    dest: $HOME/code/scripts/ansible/swarm.sh
      #
      #  handlers:
      #    - name: join swarm
      #      debug: msg="Joining swarm"
      #      command: {{ join_cmd }}
      #      #when: swarm_token|success

    #nodename: "{{ ansible_hostname | regex_replace('_lead$', '') }}"
    #FUBAR="{{ ( PREFIX + '_' + CNAME + VERSION ) | replace('.','') }}"
    #
    #
    #- debug: msg={{ ansible_nodename }}
    #- debug: msg={{ machine_name }}
    #- debug: msg={{ ansible_host }}
    #
    #
    #shell: |
    #  rm $HOME/{{ bot_gpg_name }}.asc
    #  rm $HOME/{{ tmp_pubkeylist }}"
    #
    #
    #
    #vars:
    #  app: "{{ app_definitions }}"
    #tasks:
    #  - name: json output
    #    debug:
    #      msg:
    #      - "My item is {{ item }}"
    #      - "{{ app[item] }}"
    #    with_items:
    #      - "{{ app | list }}"
    #
    #
    #
#   - name: write blue service
#     register: output
#     shell: |
#         echo "consul kv put apps/{{ app[item].subdomain_name }}/green {{ app[item].green_service }}"
#         echo "consul kv put apps/{{ app[item].subdomain_name }}/blue {{ app[item].blue_service }}"
#         echo "consul kv put apps/{{ app[item].subdomain_name }}/active {{ app[item].default_active }}"
#         echo "consul kv put applist/{{ app[item].service_name }} {{ app[item].subdomain_name }}"
#     debug:
#       msg: "consul kv put apps/{{ app[item].subdomain_name }}/blue {{ app[item].blue_service }}"
#     with_items:
#       - "{{ app | list }}"

#   - name: out
#     debug:
#       msg: "{{ item.stdout_lines }}"
#     with_items:
#       - "{{ output.results }}"
#
#
    - meta: end_play
#
#  vars:
#    redis: "{{ redis_dbs | from_json }}"
#    mongo: "{{ mongo_dbs | from_json }}"
#    pg: "{{ pg_dbs | from_json }}"
#    dbs_to_import: "{{ dbs_to_import | from_json }}"
#    use_gpg: "{{ use_gpg }}"
#    bot_gpg_name: "{{ bot_gpg_name }}"
#  tasks:
#
#    - name: test
#      debug:
#        msg:
#        - "redis {{ redis }}"
#        - "mongo {{ mongo }}"
#      when: mongo
#
#    - name: test
#      debug:
#        msg:
#        - "{{ hostvars[ansible_host]['ansible_'+vpc_private_iface].ipv4.address }}"
