ARG BASE_IMAGE=alpine
ARG BASE_IMAGE_TAG=3.14

FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}

ARG KUBE_VERSION=1.22.1
ENV KUBE_VERSION=$KUBE_VERSION

RUN apk add --update ca-certificates \
    && apk add --update bash git curl \
    && curl -L https://dl.k8s.io/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl \
    && chmod g+rwx /usr/local/bin/kubectl \
    && rm /var/cache/apk/*

ENTRYPOINT ["bash"]
CMD [""]
