ARG BASE_IMAGE=alpine
ARG BASE_IMAGE_TAG=3.14

FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}

ARG KUBE_VERSION=1.22.1
ARG HELM_VERSION=3.8.2
ENV KUBE_VERSION=$KUBE_VERSION
ENV HELM_VERSION=$HELM_VERSION

RUN apk add --update ca-certificates \
    && apk add --update bash git curl \
    && curl -L https://dl.k8s.io/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl \
    && chmod g+rwx /usr/local/bin/kubectl \
    && curl -L https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz -o /tmp/helm-linux.tar.gz \
    && tar -xzvf /tmp/helm-linux.tar.gz --directory /tmp \
    && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
    && rm -rf /tmp/*linux* \
    && rm /var/cache/apk/*

ENTRYPOINT ["bash"]
CMD [""]
