---
- name: RE-ENABLE AUTOUPGRADES
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: re-enable autoupgrades
      shell: 'sed -i "s|0|1|" /etc/apt/apt.conf.d/20auto-upgrades'


- name: GET GITLAB INIT PW
  hosts: "{{ (groups.admin | length > 0) | ternary( (groups.admin|first), []) }}"
  remote_user: root
  gather_facts: false
  tasks:
    - name: check if pw exists
      stat:
        path: "/etc/gitlab/initial_root_password"
      register: file_data

    - name: fetch init pw
      register: output
      command: cat /etc/gitlab/initial_root_password
      when: file_data.stat.exists

    - name: out
      debug:
        msg: "{{ output.stdout_lines }}"
      when: file_data.stat.exists
