app:
  image:
    tag: "{{ item.0.value.image_tag }}"
  svcDiscovery:
    consul:
      enabled: true
      env:
        CONSUL_HOST: consul.{{ root_domain_name }}
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: wekan.{{ root_domain_name }}
    tls:
      - hosts:
          - wekan.{{ root_domain_name }}
        secretName: wekan-tls
  configMapData:
    MONGO_URL: "mongodb://{{ hostvars[groups.db[0]].private_ip }}:27017/wekan"
    ROOT_URL: "https://wekan.{{ root_domain_name }}"
    OAUTH2_SERVER_URL: "https://gitlab.{{ root_domain_name }}/"
    OAUTH2_ENABLED: true
  secretStringData:
    OAUTH2_CLIENT_ID: "{{ wekan_app_id.data | ternary(wekan_app_id.data.Value, '') }}"
    OAUTH2_SECRET: "{{ wekan_secret.data | ternary(wekan_secret.data.Value, '') }}"
