image:
  tag: "{{ item.0.value.image_tag }}"
configMapData:
  MONGO_URL: "mongodb://{{ hostvars[groups.db[0]].private_ip }}:27017/wekan"
  ROOT_URL: "https://wekan.{{ root_domain_name }}"
  OAUTH2_SERVER_URL: "https://gitlab.{{ root_domain_name }}/"
  OAUTH2_ENABLED: true
secretStringData:
  OAUTH2_CLIENT_ID: "{{ wekan_app_id.data | ternary(wekan_app_id.data.Value, '') }}"
  OAUTH2_SECRET: "{{ wekan_secret.data | ternary(wekan_secret.data.Value, '') }}"
