######################
###NOTE: Not being used
### We're keeping it as a terraform resource until we have reason to run in ansible
### Only one line in this file references an external ip and its roughly static until some
###  major refactoring to migrate admin server while entire infra is up
#####################
---
- name: Handle exporters
  hosts: all
  remote_user: root
  vars:
    nodeexporter_version: "{{ nodeexporter_version }}"
    promtail_version: "{{ promtail_version }}"
    consulexporter_version: "{{ consulexporter_version }}"
  tasks:
      #- debug: var=hostvars[inventory_hostname].private_ipv4
    - debug: var=hostvars

    - name: start nodeexporter
      command: {{ item }}
      with_items:
        - echo "hi"
      when: "admin" not in machine_name

    - meta: end_play



    - name: download nodeexporter
      shell: |
        FILENAME1=node_exporter-{{ nodeexporter_version }}.linux-amd64.tar.gz
        [ ! -f /tmp/$FILENAME1 ] && wget https://github.com/prometheus/node_exporter/releases/download/v{{ nodeexporter_version }}/$FILENAME1 -P /tmp
        tar xvfz /tmp/$FILENAME1 --wildcards --strip-components=1 -C /usr/local/bin */node_exporter

    - name: download promtail
      shell: |
        FILENAME2=promtail-linux-amd64.zip
        [ ! -f /tmp/$FILENAME2 ] && wget https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/$FILENAME2 -P /tmp
        unzip /tmp/$FILENAME2 -d /usr/local/bin && chmod a+x /usr/local/bin/promtail*amd64

        FILENAME3=promtail-local-config.yaml
        mkdir -p /etc/promtail.d
        [ ! -f /etc/promtail.d/$FILENAME3 ] && wget https://raw.githubusercontent.com/grafana/loki/main/clients/cmd/promtail/$FILENAME3 -P /etc/promtail.d
#####   sed -i \"s/localhost:/{{ admin_ip_private }}:/\" /etc/promtail.d/$FILENAME3
        sed -ni '/nodename:/!p; $ a \\      nodename: {{ machine_name }}' /etc/promtail.d/$FILENAME3

    - name: download consulexporter
      shell: |
        FILENAME4=consul_exporter-{{ consulexporter_version }}.linux-amd64.tar.gz
        [ ! -f /tmp/$FILENAME4 ] && wget https://github.com/prometheus/consul_exporter/releases/download/v{{ consulexporter_version }}/$FILENAME4 -P /tmp
        tar xvfz /tmp/$FILENAME4 --wildcards --strip-components=1 -C /usr/local/bin */consul_exporter

    - name: upload nodeexporter template
      copy:
        src: "../templatefiles/services/nodeexporter.service"
        dest: "/etc/systemd/system/nodeexporter.service"

    - name: upload consulexporter template
      copy:
        src: "../templatefiles/services/consulexporter.service"
        dest: "/etc/systemd/system/consulexporter.service"

    - name: upload promtail template
      copy:
        src: "../templatefiles/services/promtail.service"
        dest: "/etc/systemd/system/promtail.service"

    - name: start promtail
      command: {{ item }}
      with_items:
        - sudo systemctl start promtail
        - sudo systemctl enable promtail

    - name: start consulexporter
      command: {{ item }}
      with_items:
        - sudo systemctl start consulexporter
        - sudo systemctl enable consulexporter
      when: "admin" in machine_name

    - name: start nodeexporter
      command: {{ item }}
      with_items:
        - sudo systemctl start nodeexporter
        - sudo systemctl enable nodeexporter
      when: "admin" not in machine_name
