---
- name: HANDLE CONSUL KV
  hosts: "{{ (groups['admin'] | default([]) + groups['lead']) | first }}"
  remote_user: root
  gather_facts: no
  vars:
    app: "{{ app_definitions }}"
    ssl: "{{ additional_ssl }}"
    root_domain_name: "{{ root_domain_name }}"
    pg_password: "{{ pg_password }}"
    dev_pg_password: "{{ dev_pg_password }}"
  tasks:
    - name: delete applist
      command: consul kv delete -recurse applist

    - name: write app_definitions kv
      shell: |
        consul kv put applist/{{ app[item].service_name }} {{ app[item].subdomain_name }}
      with_items:
        - "{{ app | list }}"

    - name: write additional_ssl kv
      shell: |
        consul kv put applist/{{ item.service_name }} {{ item.subdomain_name }}
      with_items:
        - "{{ ssl | list }}"

    - name: write misc cluster kv
      shell: |
        consul kv put domainname {{ root_domain_name }}
        consul kv put PG_PASSWORD {{ pg_password }}
        consul kv put DEV_PG_PASSWORD {{ dev_pg_password }}
