# For kubernetes 1.20 use digitalocean csi 3.0.0
# https://github.com/digitalocean/csi-digitalocean/blob/master/deploy/kubernetes/releases/csi-digitalocean-v3.0.0/snapshot-validation-webhook.yaml
# https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes/webhook-example

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validation-webhook.snapshot.storage.k8s.io"
webhooks:
  - name: "validation-webhook.snapshot.storage.k8s.io"
    rules:
      - apiGroups:   ["snapshot.storage.k8s.io"]
        apiVersions: ["v1", "v1beta1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["volumesnapshots", "volumesnapshotcontents"]
        scope:       "*"
    clientConfig:
      service:
        namespace: "{{ csi_namespace }}"
        name: "snapshot-validation-service"
        path: "/volumesnapshot"
      caBundle: {{ ca_bundle.stdout }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-validation
  namespace: {{ csi_namespace }}
  labels:
    app: snapshot-validation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snapshot-validation
  template:
    metadata:
      labels:
        app: snapshot-validation
    spec:
      containers:
        - name: snapshot-validation
          image: k8s.gcr.io/sig-storage/snapshot-validation-webhook:v3.0.3
          imagePullPolicy: IfNotPresent
          args: ['--tls-cert-file=/etc/snapshot-validation-webhook/certs/cert.pem', '--tls-private-key-file=/etc/snapshot-validation-webhook/certs/key.pem']
          ports:
            - containerPort: 443
          volumeMounts:
            - name: snapshot-validation-webhook-certs
              mountPath: /etc/snapshot-validation-webhook/certs
              readOnly: true
      volumes:
        - name: snapshot-validation-webhook-certs
          secret:
            secretName: {{ snapshot_secret_name }}

---

apiVersion: v1
kind: Service
metadata:
  name: snapshot-validation-service
  namespace: {{ csi_namespace }}
spec:
  selector:
    app: snapshot-validation
  ports:
    - protocol: TCP
      port: 443
