## https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-subdomains
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
{% for service in services %}
      - {{ service.subdomain }}
{% endfor %}
    secretName: {{ tls_secret_name }}
  rules:
{% for service in services %}
  - host: "{{ service.subdomain }}"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ service.name }}
            port:
              number: 80
      - path: "/.well-known"                                   
        pathType: Prefix
        backend:
          service:
            name: cert-redirect
            port:
              number: 80
{% endfor %}

