## First iteration for migration from docker swarm to kubenernetes for some apps
## Lot less templating for general and more specific for now

- name: LAUNCH MISC SERVICES
  hosts: "{{ groups.lead | first }}"
  remote_user: root
  vars:
    apps: "{{ kube_apps | from_json }}"
    root_domain_name: "{{ root_domain_name }}"
  tasks:
    - name: launch apps
      register: out
      shell: |
        REPO_URL={{ apps[item].repo_url }}
        REPO_NAME={{ apps[item].repo_name }}
        IMAGE_TAG={{ apps[item].image_tag }}

        if [ "$REPO_NAME" = "wekan" ]; then
            git clone $REPO_URL /root/repos/$REPO_NAME;

            MONGO_IP={{ hostvars[groups.db[0]].private_ip }};
            MONGO_URL="mongodb://$MONGO_IP:27017/wekan";

            FQDN={{ root_domain_name }};
            ROOT_URL="https://wekan.$FQDN";
            OAUTH2_SERVER_URL="https://gitlab.$FQDN";

            APP_ID=$(consul kv get wekan/app_id);
            SECRET=$(consul kv get wekan/secret);

            helm upgrade --install wekan /root/repos/$REPO_NAME/helmchart \
                --set image.tag="$IMAGE_TAG" \
                --set configMapData.MONGO_URL="$MONGO_URL" \
                --set configMapData.ROOT_URL="$ROOT_URL" \
                --set configMapData.OAUTH2_SERVER_URL="$OAUTH2_SERVER_URL" \
                --set configMapData.OAUTH2_ENABLED=true \
                --set secretStringData.OAUTH2_CLIENT_ID="$APP_ID" \
                --set secretStringData.OAUTH2_SECRET="$SECRET" \
                --namespace production \
                --wait
        fi
      loop: "{{ apps | list }}"

    - name: output
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ out.results }}"
