apiVersion: v1
kind: Namespace
metadata:
  name: ${buildkitd_namespace}
  labels:
    name: ${buildkitd_namespace}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: buildkitd
  name: buildkitd
  namespace: ${buildkitd_namespace}
spec:
  serviceName: buildkitd
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      nodeSelector:
        type: main
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "main"
          effect: "NoSchedule"
      containers:
      - name: buildkitd
        image: moby/buildkit:v${buildkitd_version}
        readinessProbe:
          exec:
            command:
              - buildctl
              - debug
              - workers
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
              - buildctl
              - debug
              - workers
          initialDelaySeconds: 5
          periodSeconds: 30
        securityContext:
          privileged: true
